apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: build-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  pipelineSpec:
    workspaces:
      - name: shared-workspace

    tasks:
      - name: clone
        taskRef:
          name: git-clone
          kind: ClusterTask
        params:
          - name: url
            value: "{{ repo_url }}"
        workspaces:
          - name: output
            workspace: shared-workspace

      - name: build
        runAfter: ["clone"]
        taskRef:
          name: buildah
          kind: ClusterTask
        params:
          - name: IMAGE
            value: image-registry.openshift-image-registry.svc:5000/romanyuvan-dev/podman-openshift:latest
        workspaces:
          - name: source
            workspace: shared-workspace

  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi